# Используем базовый образ Python
FROM python:3.9

# Создаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt
COPY requirements.txt ./

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем остальные файлы проекта
COPY . .

# Указываем команду для запуска приложения
CMD ["python", "app.py"]

# Открываем порт (например, 5000)
EXPOSE 5000